apiVersion: skaffold/v4beta8
kind: Config

profiles:
  - name: knative-install
    manifests:
      rawYaml:
        - https://github.com/knative/serving/releases/download/knative-v1.12.2/serving-crds.yaml

  - name: knative-deploy
    manifests:
      kustomize:
        paths:
          - base
