apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://github.com/knative/serving/releases/download/knative-v1.12.2/serving-core.yaml
  - https://github.com/knative/net-kourier/releases/download/knative-v1.12.2/kourier.yaml

configMapGenerator:
  - name: config-network
    namespace: knative-serving
    behavior: merge
    env: kourier.properties
    options:
      disableNameSuffixHash: true
