apiVersion: skaffold/v4beta8
kind: Config

profiles:
  - name: knative-install
    manifests:
      rawYaml:
        - base/manifests/operator.yaml

  - name: knative-deploy
    manifests:
      kustomize:
        paths:
          - base
